### ISSUE TITLE
favicon-format

### ISSUE THREAD

**Issue by felix-d1strict** [AdyStudios/LogiReader#4]
Hello,

the format of the [favicon ](https://github.com/AdyStudios/LogiReader/blob/b1fec0ceebe1377efd93718635a4a18daf4f383b/public/favicon.ico) should be Rectangular.
At best, you should provide it in several versions. There is a good tool for this: https://realfavicongenerator.net/

Unfortunately I can't create a PR for it, because I don't have the original file.

**Comment by AdyStudios** [comment]
The icon was just a placeholder, because I was bored of the template. It was throgh together in paint, I want to make a better icon later. Thanks for the tip!
