### ISSUE TITLE
Display Excel-Data

### ISSUE THREAD

**Issue by felix-d1strict** [AdyStudios/LogiReader#6]
Hello,

In reference to your "todo-comment":
https://github.com/AdyStudios/LogiReader/blob/0b06c09c8a577d8cc9bf63d4bd5f91efad7e3308/src/App.jsx#L40

Do you have sample datasets that can be used here? Unfortunately, I do not have access to LogiScool.

**Comment by AdyStudios** [comment]
Yes sorry, I'll provide it here: 

[SurveyAnswers-20230811185844739.xlsx](https://github.com/AdyStudios/LogiReader/files/12545906/SurveyAnswers-20230811185844739.xlsx)

**Comment by felix-d1strict** [comment]
Thanks! Are all Datasets like this? Or is something sometimes different? @AdyStudios
